# config.yml
experiment:
  name: "multimodal_cancer_prediction"
  output_dir: "results/experiments"

cv_params:
  outer_repeats: 2
  outer_folds: 2
  inner_folds: 2
  validation_split: 0.3
  stratify: true

parallel:
  backend: "future"
  workers: 4
  strategy: "multisession"

model:
  print_every: 1
  architecture:
    dropout: 0.2
    modality_dims:
      clinical: 64     
      expression: 256  
      mutations: 64    
      methylation: 256 
      mirna: 256      
      cnv: 256        
    encoder_dims:
      clinical: [32]
      expression: [32]
      mutations: [32]
      methylation: [32]
      mirna: [32]
      cnv: [32]
    fusion_dim: 64
    attention:
      intra_modality:  # New section for intra-modality attention
        enabled: true
        num_heads: 2
        dropout: 0.1
        pre_norm: true  # Whether to use pre-norm or post-norm
      cross_modality:   # New cross-attention config
        enabled: true
        num_heads: 2
        dropout: 0.1
      global:          # Attention after fusion
        enabled: true
        num_heads: 2
        dropout: 0.1      

  # Rest of the config remains the same
  batch_size: 32
  max_epochs: 2
  early_stopping:
    patience: 10
    min_delta: 0.001
  optimizer:
    name: "adam"
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: "reduce_on_plateau"
    patience: 5
    factor: 0.5
